create database e_commerce;
use e_commerce;
select * from `e-commerce`;
select sum(stockcode) from `e-commerce`;
select sum(Quantity) from `e-commerce`;
select avg(UnitPrice) from `e-commerce`;
select min(UnitPrice) from `e-commerce`;
select max(UnitPrice) from `e-commerce`;
select distinct(Country) from `e-commerce`;
select sum(Quantity),Country from `e-commerce` group by Country order by sum(Quantity) desc;
select Country,count(*) as total_transactions from `e-commerce`group by Country order by total_transactions desc;
select count(*) as transactions from `e-commerce`;
select Country,count(*) as total_transactions from `e-commerce` where country="United Kingdom";
select count(*) as transactions,UnitPrice from `e-commerce`group by Unitprice having UnitPrice > 10;
select sum(Quantity) as total_Quantity from `e-commerce`;
select sum(Quantity) as total_quantity,Description from  `e-commerce` group by Description order by total_quantity ;
select avg(UnitPrice),max(UnitPrice),min(Unitprice) from  `e-commerce` ;
select Quantity,UnitPrice,(Quantity*UnitPrice) as total_sales from `e-commerce`;
with country_sales as (select `Country`, sum(`Quantity`*`UnitPrice`) as total_sales from `e-commerce` group by `Country`) select `Country`,total_sales from country_sales where total_sales > 50;
select CustomerID,sum(Quantity * UnitPrice) as total_spending from `e-commerce` group by CustomerID having sum(Quantity * UnitPrice) > (select avg(total_spending) from (select CustomerID,sum(Quantity * UnitPrice) as total_spending from `e-commerce` group by CustomerID) as customer_spending);
select Country,sum(Quantity * UnitPrice) AS total_sales, rank() over (order by sum(Quantity * UnitPrice) desc) as sales_rank from `e-commerce` group by Country;
with monthly_sales as (select date_format(InvoiceDate, '%Y-%m') as month,sum(Quantity * UnitPrice) as total_sales from `e-commerce` group by month) select month,total_sales,lag(total_sales) over (order by month) as previous_month_sales from monthly_sales order by month;
select Country,sum(Quantity * UnitPrice) as total_sales from `e-commerce` group by Country order by total_sales desc limit 5;
select CustomerID,sum(Quantity * UnitPrice) as total_spend from `e-commerce` group by CustomerID order by total_spend desc limit 10;
select Description,sum(Quantity * UnitPrice) as revenue from `e-commerce` group by Description order by revenue desc limit 10;
